### ISSUE TITLE
2021.6 amber_electric component won't run, requires version in manifest

### ISSUE THREAD

**Issue by mikemortimer** [lewisbenge/hass-amber-electric#26]
Been warning for a while that custom components need the version in the manifest otherwise they'll be unsupported on 2021.6 - well, time has come. Should be a pretty quick fix...?

**Comment by davewatson91** [comment]
read through all the issues please.

**Comment by talikarng** [comment]
Particularly read issue #25 - the API that underpins this repo is being retired. We'll have to wait for the new one which is hopefully not too far away.

**Comment by mikemortimer** [comment]
Yes, thanks - I did. It takes literally 2 seconds to add one line to the manifest so that people using this now can continue until then

**Comment by davewatson91** [comment]
It has been added - in the fork that is mentioned in basically every other issue - unfortunately the original hasn't been udpated in quite a while. 

https://github.com/davewatson91/hass-amber-electric

**Comment by mikemortimer** [comment]
Ah, fair enough. I'll take a look at the fork, thanks. Although I might just disable it for now, the API doesn't seem to be showing the same as the app real time at all anymore (showing 62c currently when the app is showing 25... so it looks like it's just completely unusable now anyway 😢
