### ISSUE TITLE
Could you add the controlled load tariff?

### ISSUE THREAD

**Issue by stuarts0011** [lewisbenge/hass-amber-electric#6]
This is great work. Thanks so much!

**Comment by rbhr** [comment]
+1 to the request and ++1 for the great work!

**Comment by adavis59** [comment]
+1 to the request !

**Comment by lewisbenge** [comment]
I've asked the question to Amber to see whether this data is on the API stream and can be exposed in the sensor

**Comment by joho** [comment]
The data under the E2 key in staticPrices is controlled load

**Comment by lewisbenge** [comment]
Thanks John! You can close my support ticket now :)

**Comment by joho** [comment]
I've gone and closed the ticket.

`totalFixedKWHPrice`  is the one you want.

**Comment by lewisbenge** [comment]
@stuarts0011, @rbhr can you please confirm if you'd like the controlled load value exposed as a 3rd sensor or just a parameter on the existing sensor?

**Comment by stuarts0011** [comment]
It would be great to expose as a third sensor. Thanks

**Comment by rbhr** [comment]
That would be fantastic. Thank you!

**Comment by lewisbenge** [comment]
This sensor has now been added, and has been merged into main under #17
