### ISSUE TITLE
Sensor is returning the price in the previous period.

### ISSUE THREAD

**Issue by stuarts0011** [lewisbenge/hass-amber-electric#7]
The sensors are displaying the price for the preceding 30 minute period, not the current.   

This is also reflected in the fact that there are two attribute readings for the ACTUAL price, but the first is for the preceding period.  The second is the correct one and what the sensor should be returning.

**Comment by stuarts0011** [comment]
To fix this, in Lines 82 and 87 of senor.py change "0" to "1"

**Comment by adavis59** [comment]
What about a way to compare if price displayed is accurate with Post code set/time zone?

**Comment by stuarts0011** [comment]
It seems that there are no longer two attribute readings for the ACTUAL price, so the reference to "1" does not need to be updated. Amber must be fiddling with their API.

**Comment by madpilot** [comment]
PR #12 fixes this.

**Comment by OmgImAlexis** [comment]
@lewisbenge this can be closed, fixed in #12
