### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by adavis59** [lewisbenge/hass-amber-electric#8]
When reveiwing the State of "sensor.amber_general_usage_price" entity.
last_update: '2020-06-27 12:48:17
State: 20.53

As you can see below, True time is 22.31. 

  - pricing_period_type: ACTUAL
    pricing_period: '2020-06-27 23:00:00'
    renewable_percentage: 0.05
    price: 22.54
  - pricing_period_type: FORECAST
    pricing_period: '2020-06-27 23:30:00'
    renewable_percentage: 0.05

**Comment by stuarts0011** [comment]
No its working correctly. the ACTUAL reading is the current forecast average price for the 30 minute period ending 23:00:00. It gets updated about every 5 minutes as the wholesale price changes.

**Comment by adavis59** [comment]
Readme says: 
_"...2 sensors added to your Home Assistant entities list, one reflects the current solar feed-in tarrif, and the second is the real-time grid price charged by Amber..._"

It is not displaying Current Solar feed-in tarrif, or Rear-time grid price. 

AMBER app/ website real-time grid pirce:  **32 c/kWh.**
Time right now:  **17:22**

Price being displayed in Hass.io is **21.59 c/kWh.**
last update 2020-06-28 **07:49:24**

^^ above price is from   **pricing_period: '2020-06-28 07:30:00'**,  see below Forecast:

Price_Forecast:
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 07:30:00'
  renewable_percentage: 0.18
  price: 21.59
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 08:00:00'
  renewable_percentage: 0.18
  price: 22.05
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 08:30:00'
  renewable_percentage: 0.17
  price: 22.12
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 09:00:00'
  renewable_percentage: 0.23
  price: 22.11
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 09:30:00'
  renewable_percentage: 0.32
  price: 22.01
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 10:00:00'
  renewable_percentage: 0.37
  price: 21.86
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 10:30:00'
  renewable_percentage: 0.45
  price: 21.72
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 11:00:00'
  renewable_percentage: 0.5
  price: 21.1
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 11:30:00'
  renewable_percentage: 0.55
  price: 20.91
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 12:00:00'
  renewable_percentage: 0.58
  price: 20.13
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 12:30:00'
  renewable_percentage: 0.61
  price: 20.2
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 13:00:00'
  renewable_percentage: 0.61
  price: 20.07
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 13:30:00'
  renewable_percentage: 0.61
  price: 19.54
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 14:00:00'
  renewable_percentage: 0.6
  price: 19.82
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 14:30:00'
  renewable_percentage: 0.57
  price: 20.13
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 15:00:00'
  renewable_percentage: 0.52
  price: 20.47
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 15:30:00'
  renewable_percentage: 0.46
  price: 20.57
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 16:00:00'
  renewable_percentage: 0.37
  price: 21.47
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 16:30:00'
  renewable_percentage: 0.27
  price: 23.04
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 17:00:00'
  renewable_percentage: 0.17
  price: 23.23
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 17:30:00'
  renewable_percentage: 0.07
  price: 35.48
- pricing_period_type: ACTUAL
  pricing_period: '2020-06-28 18:00:00'
  renewable_percentage: 0.04
  price: 26.02
- pricing_period_type: FORECAST
  pricing_period: '2020-06-28 18:30:00'
  renewable_percentage: 0.04
  price: 26.42
- pricing_period_type: FORECAST
  pricing_period: '2020-06-28 19:00:00'
  renewable_percentage: 0.06
  price: 25.73

**Comment by stuarts0011** [comment]
> Readme says:
> _"...2 sensors added to your Home Assistant entities list, one reflects the current solar feed-in tarrif, and the second is the real-time grid price charged by Amber..._"
> 
> It is not displaying Current Solar feed-in tarrif, or Rear-time grid price.
> 
> AMBER app/ website real-time grid pirce: **32 c/kWh.**
> Time right now: **17:22**
> 
> Price being displayed in Hass.io is **21.59 c/kWh.**
> last update 2020-06-28 **07:49:24**
> 
> ^^ above price is from **pricing_period: '2020-06-28 07:30:00'**, see below Forecast:
> 
> Price_Forecast:
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 07:30:00'
>       renewable_percentage: 0.18
>       price: 21.59
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 08:00:00'
>       renewable_percentage: 0.18
>       price: 22.05
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 08:30:00'
>       renewable_percentage: 0.17
>       price: 22.12
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 09:00:00'
>       renewable_percentage: 0.23
>       price: 22.11
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 09:30:00'
>       renewable_percentage: 0.32
>       price: 22.01
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 10:00:00'
>       renewable_percentage: 0.37
>       price: 21.86
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 10:30:00'
>       renewable_percentage: 0.45
>       price: 21.72
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 11:00:00'
>       renewable_percentage: 0.5
>       price: 21.1
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 11:30:00'
>       renewable_percentage: 0.55
>       price: 20.91
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 12:00:00'
>       renewable_percentage: 0.58
>       price: 20.13
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 12:30:00'
>       renewable_percentage: 0.61
>       price: 20.2
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 13:00:00'
>       renewable_percentage: 0.61
>       price: 20.07
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 13:30:00'
>       renewable_percentage: 0.61
>       price: 19.54
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 14:00:00'
>       renewable_percentage: 0.6
>       price: 19.82
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 14:30:00'
>       renewable_percentage: 0.57
>       price: 20.13
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 15:00:00'
>       renewable_percentage: 0.52
>       price: 20.47
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 15:30:00'
>       renewable_percentage: 0.46
>       price: 20.57
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 16:00:00'
>       renewable_percentage: 0.37
>       price: 21.47
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 16:30:00'
>       renewable_percentage: 0.27
>       price: 23.04
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 17:00:00'
>       renewable_percentage: 0.17
>       price: 23.23
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 17:30:00'
>       renewable_percentage: 0.07
>       price: 35.48
> 
>     * pricing_period_type: ACTUAL
>       pricing_period: '2020-06-28 18:00:00'
>       renewable_percentage: 0.04
>       price: 26.02
> 
>     * pricing_period_type: FORECAST
>       pricing_period: '2020-06-28 18:30:00'
>       renewable_percentage: 0.04
>       price: 26.42
> 
>     * pricing_period_type: FORECAST
>       pricing_period: '2020-06-28 19:00:00'
>       renewable_percentage: 0.06
>       price: 25.73

Look at my response to the other issue. You need to amend sensor.py

**Comment by OmgImAlexis** [comment]
@lewisbenge this can be closed, fixed in #12
